### ISSUE TITLE
Doesn't work with version 8.2.1

### ISSUE THREAD

**Issue by Khidirov** [ferib/PacketTracerRecovery#8]
Sir, thank you for a such nice tool. It was helping me in lab practice till 8.2.0 version, as 8.2.1 released program says:
Failed finding location, already patched?
By printing 'PatchOffsetLocation' I get 0 every time. I might be wrong, but I think AOBScan troubles in memory access due to the update.
```
            PatchOffsetLocation = AOBScan(wHandle, ref OriginalCode);
            //NOP everything after 15 bytes
            for(int i = 15; i < OriginalCode.Length; i++)
                OriginalCode[i] = 0x90;
            //PatchOffsetLocation = AOBScan(wHandle, DetourPattern) +3;
            if (PatchOffsetLocation > 0x0100)
            {
#if DEBUG
                Console.WriteLine("Placing hook at 0x" + PatchOffsetLocation.ToString("X"));
#endif
                //Console.WriteLine("Hooking data..");
            }
            else
            {
                // Added for debugging
		Console.WriteLine(PatchOffsetLocation);
                Console.WriteLine("Failed finding location, already patched?");
                return;
            }
```
P.S. If there is a way to force use 8.2.0 version, would be glad to hear it.

**Comment by ferib** [comment]
Hello, you would most likely need to update the pattern at https://github.com/ferib/PacketTracerRecovery/blob/master/Program.cs#L102 as the search no longer finds the correct location. Please compare `8.2.0` with `8.2.1` to see what changed and update the byte pattern accordingly.

**Comment by Khidirov** [comment]
> Hello, you would most likely need to update the pattern at https://github.com/ferib/PacketTracerRecovery/blob/master/Program.cs#L102 as the search no longer finds the correct location. Please compare `8.2.0` with `8.2.1` to see what changed and update the byte pattern accordingly.

Probably I am not quite experienced to do that, as attempts with task manager and cheat engine to catch pka process failed. Could you please fix it?

**Comment by ferib** [comment]
Sorry, but these things aren't worth my time anymore.

I would be happy to see you succeed on this one :)

**Comment by Jerem584** [comment]
https://github.com/Jerem584/PacketTracerRecovery

here is for 8.2.1
